version: '3.8'

services:
  neverland.aliyun.ddns:
    container_name: ALIYUN-DDNS
    networks:
      - product-network
    environment:
      - ALIKID=
      - ALIKSCT=
      - ALIDOMAIN=ilyl.life
      - ALITTL=600
networks:
  product-network:
    driver: bridge